### ISSUE TITLE
Enhance Exploration and Add Item Usage Command  

### ISSUE THREAD

**Issue by Shivg2901** [opencodeiiita/CLI-For-You#13]
### **Description:**  
Introduce new functionality to improve the exploration command and implement item usage and weapon management systems.  

---

#### **Enhanced Exploration Command**  
- Update the `explore` command to **randomly** generate item discoveries.  
  - Possible outcomes:  
    - Discover items (e.g., Health Potion, Weapon).  
    - Find nothing (e.g., "You found nothing... better luck next time.").  

#### **Use Command (`use <item>`)**  
- Allow players to use items from their inventory:  
  - **Health Potions:**  
    - Restores player HP.  
    - Removed from inventory after use.  
  - **Weapons:**  
    - Temporarily boosts attack damage.  
    - Remains in the inventory after use for repeated application.  

#### **Drop Command (`drop <weapon>`)**  
- Enable players to unequip the currently equipped weapon while keeping it in the inventory.  
  - Example: `drop sword` unequips the Sword and updates the equipped status.  
  - Feedback: *"You have unequipped the Sword. It's back in your inventory."*  

---

### **Acceptance Criteria:**  
- The `explore` command randomly generates item discoveries.  
- Players can use items with the `use <item>` command:  
  - Health Potions restore HP and are removed from inventory.  
  - Weapons temporarily boost attack damage but remain in inventory after use.  
- Players can unequip weapons using the `drop <weapon>` command, and unequipped weapons remain accessible in the inventory.  
- Provide feedback messages for all actions:  
  - Discovery: *"You found a Health Potion! Use `pickup Health Potion` to collect it."*  
  - Usage:  
    - Health Potion: *"You used a Health Potion and restored 20 HP!"*  
    - Weapon: *"You used a Sword, boosting your attack temporarily!"*  
  - Drop: *"You have unequipped the Sword. It's back in your inventory."*  
- The `inventory` command must clearly display:  
  - All collected items.  
  - The currently equipped weapon (if any).  

---

### **Additional Notes:**  
- Ensure clear error handling for invalid `use` or `drop` commands (e.g., "You don't have that item in your inventory.").  
- Attach screenshots demonstrating exploration, item usage, and weapon management functionality in the PR.  
- Prepare for future enhancements, such as weapon-specific stats or effects.

**Comment by YugDevOPs** [comment]
PHP

**Comment by SajalGarg035** [comment]
claim

**Comment by apexcoder007** [comment]
claim

**Comment by Vardaan-02** [comment]
maine code likh diya hai assign me and i will make a pull request
