### ISSUE TITLE
My-RPG/Add Inventory Management System

### ISSUE THREAD

**Issue by Shivg2901** [opencodeiiita/CLI-For-You#2]
# Adding Inventory Commands to the RPG CLI Game

## New Commands:
- **pickup <item>:** Adds an item to the player's inventory.
- **inventory:** Lists all items currently in the player's inventory.

## Define an Item class with attributes like:
- **name:** Name of the item.
- **type:** Type of the item (e.g., potion, weapon).
- **effect:** Action performed when the item is used (e.g., increase HP or attack).

## Modify the GameEngine Class:
- Add an inventory property to store items collected by the player.
- Update the handleCommand method to process the new commands (`pickup`, `inventory`, `use`).

## Display appropriate messages for actions:
- Successful item pickup: `"You picked up a Health Potion!"`
- Viewing inventory: List all items or show `"Your inventory is empty."`
- Using an item: `"You used a Health Potion and restored 20 HP!"`

For now let the player pickup any valid weapon
Kindly attach relevant screenshots
If you want the issue to be assigned to you comment below

**Comment by PriyamJChakrabarty** [comment]
claim

**Comment by Shivg2901** [comment]
@SajalGarg035 
Updates?
