### ISSUE TITLE
Implement an Interactive Initial Screen with storymode Command and Enhanced Storyline Display

### ISSUE THREAD

**Issue by Shivg2901** [opencodeiiita/CLI-For-You#27]
### **Description:**  
Design and implement an **enhanced initial screen** where the player first enters their name and is introduced to the story only after typing a specific command, such as `storymode` . This feature adds an interactive element and allows players to engage with the game at their own pace.  

---

#### **Initial Screen:**  
- Display a **welcome message** with some simple ASCII art or styling to set the tone (e.g., "Welcome to the RPG CLI Game!").  
- Prompt the player to enter their name, such as:  
  > "Enter your name to begin your adventure: [Player enters name]"  

- After entering their name, display a brief message like:
  > "Welcome, [Player Name]! Type `storymode` to begin your journey or `help` to see available commands."  

#### **Story Mode:**  
- Upon typing the `storymode` command:  
  - Create relevant **ASCII art** and be creative (e.g., borders, symbols, or visuals matching the storyline).  
  - Display the following storyline in a visually appealing format:  

    > "You awaken in a mysterious land with no memory of how you got there. The world around you is shrouded in fog, and whispers of ancient secrets fill the air. As you take your first steps, a faint voice echoes in your mind:  
    >  
    > 'The fate of this realm lies in your hands, traveler. Will you rise to the challenge or let darkness consume all?'"  

- Add a **dramatic pause** or **fade effect** for the storyline text.  
  - Example: Use gradual text display to simulate narration or suspense.  

---

### **Acceptance Criteria:**  
- After entering their name, the game greets the player and waits for the `storymode` command to proceed with the storyline.  
- The storyline is displayed in a formatted and visually appealing manner when `storymode` is typed.  
- The ASCII art and text effects enhance the player's experience.
- Attach screenshots demonstrating the workflow (name input, `storymode` command, and storyline display).  

---

### **Additional Notes:**  
- Use the following libraries to stylize and enhance the experience:  
  - **[chalk](https://www.npmjs.com/package/chalk):**  
    - Used for adding colorful text and formatting in the terminal.  
  - **[figlet](https://www.npmjs.com/package/figlet):**  
    - Used to create ASCII art for titles and headings.  
  - **[cli-progress](https://www.npmjs.com/package/cli-progress):**  
    - Useful for adding a gradual text display effect or animations.  
  - **[ora](https://www.npmjs.com/package/ora):**  
    - Adds spinners for suspense or waiting effects.  

- Test the flow to ensure it works seamlessly on standard terminal sizes (80x24 recommended).  

---

### **Example Flow:** (Feel free to be creative; this is just an example)

```plaintext
[ASCII ART HERE]
Welcome to the RPG CLI Game!  
Enter your name to begin your adventure:  

> Alex  
Welcome, Alex! Type `storymode` to begin your journey or `help` to see available commands.  

> storymode  

[ASCII ART HERE]  
You awaken in a mysterious land with no memory of how you got there.  
The world around you is shrouded in fog, and whispers of ancient secrets fill the air.  
As you take your first steps, a faint voice echoes in your mind:  

"The fate of this realm lies in your hands, traveler.  
Will you rise to the challenge or let darkness consume all?"

**Comment by HGRgamer** [comment]
claim

**Comment by official-ashutosh** [comment]
claim

**Comment by Shivg2901** [comment]
@official-ashutosh 
this issue has already been assigned
this is a first come first serve issue

**Comment by Shivg2901** [comment]
@HGRgamer 
updates??
