### ISSUE TITLE
Typing-Based Combat Mechanic with Enemy Class Creation

### ISSUE THREAD

**Issue by Shivg2901** [opencodeiiita/CLI-For-You#41]
## Description  
Implement a typing-based combat system where the player must type strings under pressure to defend against enemy attacks and deal counter-damage. Additionally, create an `Enemy` class to structure enemy attributes. Neither the `Enemy` class nor the `Typing-Based Combat Mechanism`will be directly used but prepares for future extension.

---

### 1. Typing-Based Combat System  
During combat, random strings will appear that the player must type within a specific time limit to avoid taking damage and deal counterattacks.  

**Mechanics to include:**  
- **Health bar for enemy and player.**
- If the player types the string correctly and within the time limit:  
  - Display feedback:  (just an example take defence into consideration as well)
    `"Success! You dealt X damage to the enemy!"`  
- If the player fails to type correctly or runs out of time:  
  - Display feedback:  
    `"Miss! The enemy strikes you for Y damage!"` 
- Add a timer function to track the time limit for typing each string.  
- Strings should be randomized from a predefined list or generated dynamically for variety.

### 2. Create Enemy Class  
Design an `Enemy` class with the following attributes:  
- `name`: Enemy's name.
- `hp`: Enemy health points (e.g., 50).  
- `attackDamage`: Base damage dealt to the player during failed inputs.  

> **Note:** The `Enemy` class will not be directly used yet, but hardcoded enemy details should simulate combat for testing purposes.  

---

### Typing Combat System:  
- Random strings are presented for the player to type.  
- A timer enforces a strict time limit for typing.  
- Appropriate feedback is displayed for success and failure.  

### Enemy Class Creation:  
- A new `Enemy` class is implemented with proper attributes.  
- Hardcode enemy details to simulate combat for testing.

### Output Demonstration:  (Since this is a function and is'nt being integrated into the game right now)
Demonstrate the combat system with hardcoded inputs to simulate:  
1. Successful typing within the time limit.  
2. Failure due to incorrect typing.  
3. Failure due to timeout.  

Display all relevant feedback messages for the player and enemy.

**Comment by apexcoder007** [comment]
claim

**Comment by official-ashutosh** [comment]
Claim

**Comment by Vardaan-02** [comment]
hey i think index file in game engine can use some modularity. Should i go ahead and create some files to make it modular ?

**Comment by Vardaan-02** [comment]
please check discord
