### ISSUE TITLE
QR- Decoder

### ISSUE THREAD

**Issue by shauryaaa100** [opencodeiiita/CLI-For-You#51]
## You can use any language for this task, too.
# This task is for construction of a QR code decoder.
But it is not as simple as it sounds. This is a sophisticated decoder, that takes as input also the file type that has been encoded into the QR. 
That means there can be plain text, images, audio, or anything stored in the QR. And you will have to decode it to reach to the file in the correct format.
## The inputs to be taken- the program must take these as inputs to work correctly:
- Image containing QR code(obviously ;)
- Output file name **with extension** (for example poster.png, shaurya.jpg, yashvik.txt, etc)
- **Whether the data inside the QR is of binary format or normal text format**
## Now the method to proceed with the task:
- First decode the qr using any library you want
- Now check if it is a base64 encrypted string or not.(You can do so by trying to decrypt then again encrypt it to check if it matches the original string- if it does, it is a base 64 encrypted string, else it is not.)
- If it is in base64 format, you need to decrypt the data.
- If the 3rd input(see above for inputs to be taken) says that the file is of binary format, then create the output file in binary mode and write the data(which you decrypted from base64, or which you directly got from the QR if it was not encrypted) into the file. If not binary, then write the data in the regular way to the output file.
- Save and close the file.

You have to create a new program for this QR Decoder. You need to add this program in the same folder you used for the QR encoder. If you did not do that task, create a folder inside the QR-Encoder-Decoder folder named after your github username. You have to do all your stuff inside this folder.

**This is an open-for-all task: so no need to claim it. Just submit your PRs.

## I am giving 2 test QR codes for this task. You need to decrypt these two and attach screenshots of the result in the PR. The PR must also contain the command to run the program.
![QR1](https://github.com/user-attachments/assets/494a82f4-063c-4366-a5f7-9db123068115)  This has data in binary format.
![QR2](https://github.com/user-attachments/assets/a3262a73-ddf6-4f69-9515-f0a36c9ba334)
This has data in normal format.

## Please note that the extension of file inside 1st QR is .png,  and that of 2nd file is .txt.

**Comment by Navigam1108** [comment]
Claim

**Comment by PriyamJChakrabarty** [comment]
Bruh

**Comment by apexcoder007** [comment]
claim

**Comment by shauryaaa100** [comment]
This is an open for all issue, no need to claim it.

**Comment by shauryaaa100** [comment]
Please note that the extension of file inside 1st QR is .png,  and that of 2nd file is .txt.

**Comment by YASMIN-SEKH** [comment]
Cannot download/view the qr codes it shows following error

**This private-user-images.githubusercontent.com page can’t be found**

**Comment by shauryaaa100** [comment]
Note that this task will be closed today at midnight.
