### ISSUE TITLE
Research and Identify a Suitable Node.js Library for Playing Sounds

### ISSUE THREAD

**Issue by Shivg2901** [opencodeiiita/CLI-For-You#54]
## **Objective**
Identify a Node.js library or dependency for playing sounds in our RPG CLI game that meets the following requirements.
---
### **Key Requirements:**
1. **Cross-Platform Compatibility:**
   - The library should work on major operating systems (**Windows, macOS, Linux**).

2. **Ease of Use:**
   - Should integrate easily with Node.js and support simple function calls to play specific sound files.

3. **No Extra Software Dependencies:**
   - Should not require downloading additional software (e.g., VLC) for sound playback.

4. **Sound Quality:**
   - Must ensure **normal, undistorted playback quality**.

---

## **Tasks for Contributor**

1. **Create a folder called Sound and inside it create a folder by your github ID**
   - Add all the relevant files inside this folder

2. **Find and Recommend:**
   - Research and identify **the best library** that fulfills the requirements.
   - Provide **alternative libraries** in case the first choice has issues.

3. **Test and Validate:**
   - Test the libraries on at least **two operating systems** (e.g., Windows + macOS/Linux).
   - Confirm that they work without requiring extra software or configurations.

4. **Provide Proof of Functionality:**(alternative sound type also works)
   - Create a small script demonstrating the library in action by playing an **MP3 file**.
   - Upload:
     - The **MP3 file** used in testing.
     - A **recording of the script running and playing the sound**.

5. **Summarize Findings:**
   - List the recommended library and alternatives.
   - Mention pros and cons of the libraries (if any).

---

## **Deliverables**
1. A **small script** showcasing sound playback using the recommended library.
2. The **MP3 file** used for testing.
3. A **recording of the script in action**, proving it works.
4. A **summary of findings**, including the chosen library and its alternatives.

---

## **Acceptance Criteria**
- The recommended library fulfills the outlined requirements.
- Proof of functionality is provided through code, testing, and recordings.
- The submission is simple and does not include overly complex libraries or additional software.

---

## **Additional Notes**
- Use libraries with **active support and documentation**.
- Ensure the libraries are free or open-source for contributors to use.

##**This is a competitive issue there is no need to claim**
##The best and most informative contributions will get full points

**Comment by apexcoder007** [comment]
claim

**Comment by Shivg2901** [comment]
Update
It is a competitive issue
Sorry for the confusion
