### ISSUE TITLE
Refactor Combat Mechanism and Integrate with Story

### ISSUE THREAD

**Issue by Shivg2901** [opencodeiiita/CLI-For-You#63]
### Description
The combat mechanism in `combat.js` works fine as a standalone module but causes issues when integrated into the story. This issue focuses on fixing the combat mechanism and seamlessly integrating it into the story module.

### Scope of Work
1. **Refactor the combat mechanism in `combat.js`:**
   - Fix asynchronous input handling to ensure smooth gameplay.
   - Use libraries like `inquirer` to manage user inputs.
   - Address timing and progress bar issues to prevent overlaps or inconsistencies.
   - Support typing-based challenges with timed inputs and proper health/attack updates.
   - Ensure the code is modular and clean (e.g., separate input handling, combat logic, and display functions).

2. **Integrate the updated combat mechanism with the story module:**
   - Update import statements in the story module to use the refactored `combat.js`.
   - Ensure combat begins and resolves correctly without disrupting the story flow.
   - Maintain compatibility with existing story commands like `explore` and `pick`.

3. **Develop and integrate appropriate enemies:**
   - Define enemy attributes such as `name`, `health`, `attack power`, and `typing challenges`.
   - Create enemies that fit the story’s context and enhance gameplay.

### Guidelines for Contributors
1. **Focus Area:**
   - Do not modify the overall story logic; only integrate the refactored combat system.
   - Keep changes limited to `combat.js` and the necessary adjustments in the story module.

2. **Testing Requirements:**
   - Ensure combat transitions smoothly during gameplay without breaking the story flow.
   - Validate user inputs, health/attack calculations, and timing logic.
   - Test with a variety of enemies to confirm proper integration.

3. **Implementation Tips:**
   - Avoid hardcoding values; make features configurable (e.g., time limits, challenge strings).
   - Keep the player experience intuitive and engaging.

### Acceptance Criteria
1. The combat mechanism in `combat.js` is refactored for modularity and improved asynchronous handling.
2. The story module uses the new combat mechanism seamlessly.
3. Combat flows smoothly without disrupting the story narrative.
4. A variety of well-designed enemy types are integrated into the combat system.

### Notes
- The goal is to ensure the story and combat mechanism work seamlessly together.
- Contributors should prioritize modularity, test thoroughly, and enhance the player experience.

**Comment by official-ashutosh** [comment]
Claim
