### ISSUE TITLE
TexToImage: Implement Core Conversion Logic

### ISSUE THREAD

**Issue by Shivg2901** [opencodeiiita/CLI-For-You#81]
## Description  
Develop a core function to convert LaTeX-style mathematical expressions into PNG image files, forming the foundation of the **TexToImage** tool. The focus is on writing and testing the standalone function. Contributors are free to use suitable Node.js libraries to achieve the goal.  

---

## Tasks  
1. **Set Up Dependencies**  
   - Suggested libraries:  
     - **[KaTeX](https://katex.org/):** Render LaTeX strings into HTML.  
     - **[Node-canvas](https://github.com/Automattic/node-canvas):** Generate PNG images.  
   - Contributors can use alternatives if they fit the requirements and maintain project compatibility.  

2. **Implement Core Functionality**  
   - Create a file named `converter.js` inside the `TexToImage/src` folder.  
   - Write a function named `convertLatexToImage` that:  
     - Accepts:  
       - A LaTeX string (e.g., `\frac{a}{b}`)  
       - Optional dimensions: `{ width: number, height: number }`  
       - An optional output path (default: `./output/`).  
     - Processes:  
       - Uses the library to render the LaTeX string.  
       - Generates a PNG file using a drawing context (e.g., `canvas` or alternatives).  
     - Outputs: Saves the PNG to the specified path or default location.  

3. **Test Function with Hardcoded Inputs**  
   - Hardcode examples in `converter.js` to validate functionality:  
     - `\frac{a}{b}`  
     - `E = mc^2`  
     - `\int_a^b f(x) dx`  
   - Ensure generated images are:  
     - Accurate in rendering.  
     - Clear and legible.  

4. **Error Handling**  
   - Address common issues:  
     - Invalid LaTeX syntax (e.g., malformed strings).  
     - Missing output directory (auto-create if not existing).  
     - File write errors.  
---

## Expected Outcome  
- A `convertLatexToImage` function in `src/converter.js`.  
- PNG files generated and saved in the default `output/` directory or the specified path.  
- Attach screenshots of 3-4 inputs and their outputs.

**Comment by HGRgamer** [comment]
claim

**Comment by Shivg2901** [comment]
@HGRgamer You already have 3 issues at hand

**Comment by official-ashutosh** [comment]
Claim

**Comment by Shivg2901** [comment]
@saurabhk9919 
Updates ?
Check discord
